#!/bin/sh

echo 'Styling, testing and building your project before committing'

# Ensure node & npm are available
export PATH="$PATH:/usr/local/bin"

# Prettier check
npm run check-format || {
  echo "Its F**KING RAW - Your styling looks disgusting.
Prettier Check Failed. Run npm run format, add changes and try commit again."
  exit 1
}

# ESLint check
npm run lint || {
  echo "Get that weak s**t out of here!
ESLint Check Failed. Fix errors and try again."
  exit 1
}

echo 'Alright... Code looks good to me...'
echo 'Trying to create production build...'

# Build check
npm run build || {
  echo "Better call Bob... Because your build failed"
  exit 1
}

echo 'You win this time... I am committing this now.'
